# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/saba/Documents/workstation6/2d_ultrasonic_radar/2d_ultrasonic_radar.srcs/sources_1/bd/main_block_design/ip/main_block_design_rst_ps7_0_100M_0/main_block_design_rst_ps7_0_100M_0.xci
# IP: The module: 'main_block_design_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/saba/Documents/workstation6/2d_ultrasonic_radar/2d_ultrasonic_radar.srcs/sources_1/bd/main_block_design/ip/main_block_design_rst_ps7_0_100M_0/main_block_design_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_block_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/saba/Documents/workstation6/2d_ultrasonic_radar/2d_ultrasonic_radar.srcs/sources_1/bd/main_block_design/ip/main_block_design_rst_ps7_0_100M_0/main_block_design_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_block_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/saba/Documents/workstation6/2d_ultrasonic_radar/2d_ultrasonic_radar.srcs/sources_1/bd/main_block_design/ip/main_block_design_rst_ps7_0_100M_0/main_block_design_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_block_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/saba/Documents/workstation6/2d_ultrasonic_radar/2d_ultrasonic_radar.srcs/sources_1/bd/main_block_design/ip/main_block_design_rst_ps7_0_100M_0/main_block_design_rst_ps7_0_100M_0.xci
# IP: The module: 'main_block_design_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/saba/Documents/workstation6/2d_ultrasonic_radar/2d_ultrasonic_radar.srcs/sources_1/bd/main_block_design/ip/main_block_design_rst_ps7_0_100M_0/main_block_design_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_block_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/saba/Documents/workstation6/2d_ultrasonic_radar/2d_ultrasonic_radar.srcs/sources_1/bd/main_block_design/ip/main_block_design_rst_ps7_0_100M_0/main_block_design_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_block_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/saba/Documents/workstation6/2d_ultrasonic_radar/2d_ultrasonic_radar.srcs/sources_1/bd/main_block_design/ip/main_block_design_rst_ps7_0_100M_0/main_block_design_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_block_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
