# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zedboard_constraints.xdc

# Block Designs: bd/main_block_design/main_block_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_block_design || ORIG_REF_NAME==main_block_design} -quiet] -quiet

# IP: bd/main_block_design/ip/main_block_design_side_servo_0_0/main_block_design_side_servo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_block_design_side_servo_0_0 || ORIG_REF_NAME==main_block_design_side_servo_0_0} -quiet] -quiet

# IP: bd/main_block_design/ip/main_block_design_processing_system7_0_0/main_block_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_block_design_processing_system7_0_0 || ORIG_REF_NAME==main_block_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/main_block_design/ip/main_block_design_ps7_0_axi_periph_0/main_block_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_block_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==main_block_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/main_block_design/ip/main_block_design_rst_ps7_0_100M_0/main_block_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_block_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==main_block_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/main_block_design/ip/main_block_design_auto_pc_0/main_block_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_block_design_auto_pc_0 || ORIG_REF_NAME==main_block_design_auto_pc_0} -quiet] -quiet

# XDC: bd/main_block_design/main_block_design_ooc.xdc
